version: '3.8'

services:
  # App
  app:
    build:
      context: ./docker/app
      dockerfile: ./Dockerfile
    restart: unless-stopped
    ports:
      - 8000:8000
    volumes:
      - ./:/app
  # Wrangler
  wrangler:
    build:
      context: ./docker/wrangler
      dockerfile: ./Dockerfile
    restart: unless-stopped
    ports:
      - 8788:8788
    volumes:
      - ./:/app
